Actuator added in github workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,12 +39,6 @@ jobs:
             echo "No docker containers to clean up"
           fi
 
-      - name: Setup adr?
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y graphviz
-          sudo apt-get install -y python3-pip
-
       - name: Make scripts executable
         run: |
           chmod +x ./prepareAll.sh
@@ -64,6 +58,16 @@ jobs:
           echo "docker network ls"
           docker network ls
 
+      - name: Check Actuator Health
+        run: |
+          echo "Checking actuator health"
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80/actuator/health)
+          if [ "$response" != "200" ]; then
+            echo "Actuator health check failed with HTTP status: $response"
+            exit 1
+          fi
+          echo "Actuator health check passed"
+          
       - name: Run Tests
         run: ./scripts/test.sh
 
